name: ense885ay-a4
channels:
- pytorch
- menpo
- defaults
dependencies:
- jupyter
- matplotlib
- python=3.5
- parso=0.7
- scikit-learn
- scipy
- opencv3
- cyvlfeat
- pytorch-cpu
- torchvision-cpu
- pip
- pip:
  - visdom
- pyyaml
